List<String> quotes = [
  "Believe you can and you're halfway there.",
  "Strive not to be a success, but rather to be of value.",
  "The only way to do great work is to love what you do.",
  "Don't wait. The time will never be just right.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "It does not matter how slowly you go, as long as you do not stop.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "You don’t have to be great to start, but you have to start to be great.",
  "The only person you are destined to become is the person you decide to be.",
  "Failure is the condiment that gives success its flavor.",
  "The best revenge is massive success.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Don’t be afraid to give up the good to go for the great.",
  "In order to succeed, we must first believe that we can.",
  "Success is not the result of spontaneous combustion. You must set yourself on fire.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Success consists of going from failure to failure without loss of enthusiasm.",
  "The secret of success is to do the common thing uncommonly well.",
  "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Success is not about being the best. It's about being better than you were yesterday.",
  "Success is simple. Do what's right, the right way, at the right time.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Success seems to be connected with action. Successful people keep moving.",
  "Success is not in what you have, but who you are.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Success usually comes to those who are too busy to be looking for it.",
  "The successful warrior is the average man, with laser-like focus.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "To succeed in life, you need two things: ignorance and confidence.",
  "Try not to become a person of success, but rather try to become a person of value.",
  "What seems to us as bitter trials are often blessings in disguise.",
  "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.",
  "You can’t cross the sea merely by standing and staring at the water.",
  "You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals.",
  "Your true success in life begins only when you make the commitment to become excellent at what you do.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "Your dreams are what define your individuality. They have the power to give you wings and make you fly high.",
  "Your life does not get better by chance, it gets better by change.",
  "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
  "Your only limit is you.",
  "Your talent determines what you can do. Your motivation determines how much you are willing to do. Your attitude determines how well you do it."
];
